import {useState as use_state} from 'react';
import {use_catalog} from '../hooks/use_catalog.js';
import {send_workspace_request} from '../services/workspace_api.js';
import Image_upload from '../components/image_upload.jsx';
import Request_state from '../components/request_state.jsx';
export default function admin_doctor_form(){
    const state=use_catalog('specialties');const [data,set_data]=use_state({});const [pending,set_pending]=use_state(false);const [error,set_error]=use_state('');const [fields,set_fields]=use_state({});
    const labels={ho_ten:'Tên bác sĩ',email:'Email bác sĩ',mat_khau:'Mật khẩu',kinh_nghiem:'Kinh nghiệm',phi_kham:'Phí khám',bang_cap:'Bằng cấp',dia_chi_kham:'Địa chỉ khám',gioi_thieu:'Giới thiệu'};
    async function save_doctor(event){event.preventDefault();set_pending(true);set_error('');set_fields({});try{await send_workspace_request('admin/doctors',{...data,phi_kham:Number(data.phi_kham||0)});window.location.assign('/quan_tri/bac_si');}catch(failure){set_error(failure.message);set_fields(failure.fields||{});}finally{set_pending(false);}}
    return <><h1>Thêm bác sĩ</h1><Request_state {...state}/><form className="admin_form" onSubmit={save_doctor}><Image_upload value={data.anh_dai_dien} on_change={(value)=>set_data({...data,anh_dai_dien:value})}/><div className="admin_form_grid">{Object.entries(labels).map(([key,label])=><label className={`doctor_field ${key}`} key={key}>{label}{key==='gioi_thieu'?<textarea value={data[key]||''} onChange={(e)=>set_data({...data,[key]:e.target.value})}/>:<input type={key==='mat_khau'?'password':key==='email'?'email':key==='phi_kham'?'number':'text'} required={['ho_ten','email','mat_khau','phi_kham'].includes(key)} min={key==='phi_kham'?0:undefined} step={key==='phi_kham'?'0.01':undefined} autoComplete={key==='mat_khau'?'new-password':'off'} value={data[key]||''} onChange={(e)=>set_data({...data,[key]:e.target.value})}/>} {fields[key]&&<span className="field_error">{fields[key]}</span>}</label>)}<label className="doctor_field chuyen_khoa">Chuyên khoa<select required value={data.chuyen_khoa_id||''} onChange={(e)=>set_data({...data,chuyen_khoa_id:e.target.value})}><option value="">Chọn chuyên khoa</option>{state.data?.items.map((item)=><option key={item.chuyen_khoa_id} value={item.chuyen_khoa_id}>{item.ten_chuyen_khoa}</option>)}</select></label></div>{error&&<p className="form_error" role="alert">{error}</p>}<button className="primary_button" disabled={pending}>{pending?'Đang lưu…':'Thêm bác sĩ'}</button></form></>;
}
