import {useState as use_state} from 'react';
import {use_catalog} from '../hooks/use_catalog.js';
import {send_workspace_request} from '../services/workspace_api.js';
import Image_upload from '../components/image_upload.jsx';
import Request_state from '../components/request_state.jsx';
export default function admin_specialties(){
    const state=use_catalog('admin/specialties');const [editing,set_editing]=use_state(null);const [error,set_error]=use_state('');const [pending,set_pending]=use_state(false);const [remove_id,set_remove_id]=use_state('');
    async function save_specialty(event){event.preventDefault();set_pending(true);set_error('');try{await send_workspace_request(`admin/specialties${editing.chuyen_khoa_id?'/'+editing.chuyen_khoa_id:''}`,{ten_chuyen_khoa:editing.ten_chuyen_khoa||'',mo_ta:editing.mo_ta||'',anh_dai_dien:editing.anh_dai_dien||''},editing.chuyen_khoa_id?'PUT':'POST');set_editing(null);state.retry();}catch(failure){set_error(failure.message);}finally{set_pending(false);}}
    async function delete_specialty(id){set_pending(true);set_error('');try{await send_workspace_request(`admin/specialties/${id}`,{},'DELETE');set_remove_id('');state.retry();}catch(failure){set_error(failure.message);}finally{set_pending(false);}}
    return <><h1>Quản lý chuyên khoa</h1><Request_state {...state}/>{error&&<p className="form_error" role="alert">{error}</p>}<div className="specialty_admin_grid">{state.data?.items.map((item)=><article key={item.chuyen_khoa_id}><h2>{item.ten_chuyen_khoa}</h2><p>{item.so_bac_si} bác sĩ</p><button className="soft_button" onClick={()=>{set_editing(item);set_error('');}}>Chỉnh sửa</button>{remove_id===item.chuyen_khoa_id?<div><p>Xóa chuyên khoa này?</p><button className="cancel_button" disabled={pending} onClick={()=>delete_specialty(item.chuyen_khoa_id)}>Xác nhận xóa</button><button className="soft_button" onClick={()=>set_remove_id('')}>Giữ lại</button></div>:<button className="soft_button" disabled={pending} onClick={()=>set_remove_id(item.chuyen_khoa_id)}>Xóa</button>}</article>)}<button className="specialty_add" onClick={()=>{set_editing({});set_error('');}}>＋ Thêm chuyên khoa</button></div>{editing&&<form className="admin_form" onSubmit={save_specialty}><h2>{editing.chuyen_khoa_id?'Sửa chuyên khoa':'Thêm chuyên khoa'}</h2><label>Tên chuyên khoa<input required maxLength={150} value={editing.ten_chuyen_khoa||''} onChange={(e)=>set_editing({...editing,ten_chuyen_khoa:e.target.value})}/></label><label>Mô tả<textarea maxLength={2000} value={editing.mo_ta||''} onChange={(e)=>set_editing({...editing,mo_ta:e.target.value})}/></label><Image_upload value={editing.anh_dai_dien} on_change={(value)=>set_editing({...editing,anh_dai_dien:value})}/><button className="primary_button" disabled={pending}>Lưu chuyên khoa</button><button type="button" className="soft_button" onClick={()=>set_editing(null)}>Hủy chỉnh sửa</button></form>}</>;
}
