import {useState as use_state} from 'react';
import {use_catalog} from '../hooks/use_catalog.js';
import {send_workspace_request} from '../services/workspace_api.js';
import Request_state from '../components/request_state.jsx';
import Doctor_portrait from '../components/doctor_portrait.jsx';
function schedule_form({doctor}){
    const state=use_catalog(`admin/doctors/${doctor.bac_si_id}/schedules`);const [weekday,set_weekday]=use_state('2');const [start,set_start]=use_state('08:00');const [end,set_end]=use_state('11:30');const [day,set_day]=use_state(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));const [message,set_message]=use_state('');const [pending,set_pending]=use_state(false);
    async function save_schedule(event){event.preventDefault();set_pending(true);set_message('');try{await send_workspace_request(`admin/doctors/${doctor.bac_si_id}/schedules`,{thu_trong_tuan:Number(weekday),gio_bat_dau:start,gio_ket_thuc:end});state.retry();set_message('Đã thêm lịch làm việc.');}catch(error){set_message(error.message);}finally{set_pending(false);}}
    async function generate_slots(){set_pending(true);set_message('');try{const result=await send_workspace_request(`admin/doctors/${doctor.bac_si_id}/slots/generate`,{ngay_bat_dau:day,so_ngay:14});set_message(`Đã sinh ${result.created} khung giờ mới.`);}catch(error){set_message(error.message);}finally{set_pending(false);}}
    return <section className="admin_form"><h2>Lịch làm việc · {doctor.ho_ten}</h2><Request_state {...state}/><ul>{state.data?.items.map((item)=><li key={item.lich_lam_viec_id}>{item.thu_trong_tuan===8?'Chủ nhật':`Thứ ${item.thu_trong_tuan}`} · {item.gio_bat_dau}–{item.gio_ket_thuc}</li>)}</ul><form onSubmit={save_schedule}><div className="admin_form_grid"><label>Thứ<select value={weekday} onChange={(e)=>set_weekday(e.target.value)}>{[2,3,4,5,6,7,8].map((value)=><option key={value} value={value}>{value===8?'Chủ nhật':`Thứ ${value}`}</option>)}</select></label><label>Giờ bắt đầu<input type="time" step="1800" required value={start} onChange={(e)=>set_start(e.target.value)}/></label><label>Giờ kết thúc<input type="time" step="1800" required value={end} onChange={(e)=>set_end(e.target.value)}/></label></div><button className="soft_button" disabled={pending}>Thêm lịch làm việc</button></form><label>Sinh khung giờ trong 14 ngày từ<input type="date" required value={day} onChange={(e)=>set_day(e.target.value)}/></label><button className="soft_button" disabled={pending||!day} onClick={generate_slots}>Sinh khung giờ 30 phút</button>{message&&<p role="status">{message}</p>}</section>;
}
const Schedule_form=schedule_form;
export default function admin_doctors(){const state=use_catalog('admin/doctors');const [selected,set_selected]=use_state(null);return <><h1>Danh sách bác sĩ</h1><Request_state {...state}/><div className="doctor_grid">{state.data?.items.map((item)=><article className="doctor_card" key={item.bac_si_id}><Doctor_portrait doctor={item}/><h2>{item.ho_ten}</h2><p>{item.ten_chuyen_khoa}</p><button className="soft_button" onClick={()=>set_selected(item)}>Lịch làm việc</button></article>)}</div>{selected&&<Schedule_form key={selected.bac_si_id} doctor={selected}/>}</>;}
